---
# tasks file for roles/ELK

- name: Set global variables
  set_fact:
    certs_dir: "{{ certs_dir | default('/tmp/elk_certs') }}"
    elk_server_hostname: "{{ groups['ELK_Server'][0] }}"

- include_tasks: generate_certs.yml
  run_once: true

- include_tasks: server.yml
  when: "'ELK_Server' in group_names"

- include_tasks: clients.yml
  when: "'ELK_Client' in group_names"

